### ISSUE TITLE
No applications were installed

### ISSUE THREAD

**Issue by staticnotdynamic** [Magisk-Modules-Alt-Repo/com.omergoktas.Foundation#2]
Upon installing the module, I found that no applications whatsoever were installed (Bromite WebView, MicroG). However, all tweaks for settings were applied successfully. Also, applications listed in https://github.com/Magisk-Modules-Alt-Repo/com.omergoktas.Foundation/blob/master/customize.sh#L26 were uninstalled successfully.

Running crDroid 9.3 2023-04-02 build on a non-rooted device. Installed with Magisk 26.1

**Comment by omergoktas** [comment]
Rooted device is required, unfortunately (otherwise, consider this, we are trying to replace existing system apps with alternative apps (i.e., Android System Webview with Bromite Webview). We can't achieve this without getting root access)

**Comment by staticnotdynamic** [comment]
I see. Thanks for the explanation.
